<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Taxjar\SalesTax\Block\Adminhtml\Order\View\Synced $block */
$order = $block->getOrder();
$synced = $block->getSyncedAtDate($order);
if ($synced) {
    $orderSyncDate = $block->formatDate(
        new \DateTime($synced),
        \IntlDateFormatter::MEDIUM,
        true
    );
}
?>
<?php if (isset($orderSyncDate)):?>
<tr>
    <th><?= $block->escapeHtml(__('Synced to TaxJar')) ?></th>
    <td><?= $block->escapeHtml($orderSyncDate) ?></td>
</tr>
<?php endif; ?>
<script>
    require([
        'jquery',
    ], function($) {
         window.syncTransaction = function(orderId) {
             var syncButton = $('#taxjar_sync');
             syncButton.prop('disabled', true);
             syncButton.find('span').text('Syncing...');

             $.ajax({
                 url: '<?= $block->escapeUrl($block->getUrl('taxjar/transaction/sync')) ?>',
                 method: 'POST',
                 data: { order_id: orderId }
             }).done(function(res) {
                 if (res.data) {
                     window.location.reload();
                 } else {
                     alert('<?= $block->escapeHtml(__('Could not sync to TaxJar!')) ?>');
                     syncButton.prop('disabled', false);
                     syncButton.find('span').text('Sync to TaxJar');
                 }
             });
        };
    });
</script>
