<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

?>
<?php
$order = $block->getCreditmemo()->getOrder();
$creditmemo = $block->getCreditmemo();
$orderSyncDate = '';
$creditmemoSyncDate = '';

if ($block->getSyncedAtDate($order)) {
    $orderSyncDate = $block->formatDate(
        new \DateTime($block->getSyncedAtDate($order)),
        \IntlDateFormatter::MEDIUM,
        true
    );
}

if ($block->getSyncedAtDate($creditmemo)) {
    $creditmemoSyncDate = $block->formatDate(
        new \DateTime($block->getSyncedAtDate($creditmemo)),
        \IntlDateFormatter::MEDIUM,
        true
    );
}
?>
<?php if (!empty($orderSyncDate)): ?>
<tr>
    <th><?php /* @escapeNotVerified */ echo __('Order Synced to TaxJar') ?></th>
    <td><?php /* @escapeNotVerified */ echo $orderSyncDate ?></td>
</tr>
<tr>
    <th><?php /* @escapeNotVerified */ echo __('Credit Memo Synced to TaxJar') ?></th>
    <td><?php /* @escapeNotVerified */ echo $creditmemoSyncDate ?></td>
</tr>
<?php endif; ?>
