<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

?>
<p class='note'>
    <span>Validate shipping addresses and return back suggested addresses at checkout. Ensures the customer data sent to TaxJar is accurate for calculations.</span>
    <?php if (!$block->isAuthorized()) { ?>
        <span>Address validation requires a TaxJar Professional subscription. <a href="https://www.taxjar.com/how-it-works/" target="_blank">Learn more.</a></span>
    <?php } ?>
</p>

<?php if (!$block->isAuthorized()) { ?>
    <script>
        require([
            'jquery'
        ], function ($) {
            $('#tax_taxjar_address_validation').bind('DOMSubtreeModified', function (e) {
                $(this).prop('disabled', true);
            });
        });
    </script>
<?php } ?>
