<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

?>
<p class='note'><span>If enabled, does not alter your tax rates or database and instead prints debug messages for use with TaxJar support.</span></p>

<?php if ($block->isEnabled()) { ?>
    <br/>
    <ul>
        <li><strong>Magento Version:</strong> <?php echo $block->escapeHtml($block->getMagentoVersion()) ?></li>
        <li><strong>TaxJar Version:</strong> <?php echo $block->escapeHtml($block->getVersion()) ?></li>
        <li><strong>PHP Version:</strong> <?php echo $block->escapeHtml($block->getPhpVersion()) ?></li>
        <li><strong>PHP Memory Limit:</strong> <?php echo $block->escapeHtml($block->getMemoryLimit()) ?></li>
        <li><strong>Backup States:</strong> <?php echo $block->escapeHtml($block->getBackupStates()) ?></li>
        <li><strong>Backup Last Updated:</strong> <?php echo $block->escapeHtml($block->getBackupUpdate()) ?></li>
    </ul>
    <p><small><strong>Include the above information when emailing TaxJar support at support@taxjar.com.</strong><small></p>
<?php } ?>
