<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Taxjar\SalesTax\Block\Adminhtml\Order\View\Tab\Taxjar\View\Info\Calculation */

$order = $block->getOrder();
$status = $block->getOrderCalculationStatus($order);
$message = $block->getOrderCalculationMessage($order);
?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-content">
        <p><i><?= $block->escapeHtml($status); ?></i></p>
        <?php if ($message): ?>
            <br>
            <p>The following response was provided:</p>
            <p><?= $block->escapeHtml($message) ?></p>
        <?php endif; ?>
    </div>
</div>
