<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Taxjar\SalesTax\Block\Adminhtml\Order\View\Tab\Taxjar\View\Info\Calculation */

$order = $block->getOrder();
$taxResult = json_decode($block->getOrderTaxResult($order)->scalar);
$requestBody = json_decode($taxResult->request->body);
$responseBody = $taxResult->response;
?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-content">
        <span><?= $block->escapeHtml($block->getOrderCalculationStatus($order)); ?></span>
        <h2>Request</h2>
        <pre><?= $block->escapeHtml(json_encode($requestBody, JSON_PRETTY_PRINT)); ?></pre>
        <h2>Response</h2>
        <pre><?= $block->escapeHtml(json_encode($responseBody, JSON_PRETTY_PRINT));?></pre>
    </div>
</div>
