<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Taxjar\SalesTax\Block\Adminhtml\Order\View\Tab\Taxjar\View\Info\Sync */

$order = $block->getOrder();
$syncDate = $order->getData('tj_salestax_sync_date');
if ($syncDate) {
    $orderAdminDate = $block->formatDate(
        $block->getOrderSyncedAtDate($syncDate),
        \IntlDateFormatter::MEDIUM,
        true
    );
}
?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-content">
    <?php if($block->featureEnabled()): ?>
        <?php if(isset($orderAdminDate)): ?>
            <span>Last synced at <?= $orderAdminDate ?></span>
        <?php else: ?>
            <span><?= $block->escapeHtml($block->getOrderStateText($order->getState())) ?></span>
        <?php endif; ?>
    <?php else: ?>
        <span><?= $block->escapeHtml($block->getFeatureDisabledText()) ?></span>
    <?php endif; ?>
    </div>
</div>
