<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Taxjar\SalesTax\Block\Adminhtml\Order\View\Tab\Taxjar\View\Info\Sync */

$order = $block->getOrder();
$formattedDate = $block->getFormattedSyncDate($order);
?>

<div class="admin__page-section-item">
    <div class="admin__page-section-item-content taxjar-order-sync-information">
    <?php if ($block->featureEnabled()): ?>
        <?php if ($formattedDate): ?>
            <p><i>Last synced at <?= $block->escapeHtml($formattedDate) ?></i></p>
        <?php else: ?>
            <span><?= $block->escapeHtml($block->getOrderStateText($order), ['br', 'pre']) ?></span>
            <br><br>
            <span><?= $block->escapeHtml($block->getOrderActionableText($order), ['br', 'pre']) ?></span>
        <?php endif; ?>
    <?php else: ?>
        <span><?= $block->escapeHtml($block->getFeatureDisabledText(), ['br', 'pre']) ?></span>
    <?php endif; ?>
    </div>
</div>
