<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Edit $block */

$path = \Taxjar\SalesTax\Model\Configuration::TAXJAR_ADDRESS_VALIDATION;
$validateAddress = (bool) $this->helper('Taxjar\SalesTax\Helper\Data')->getConfig($path);
?>

<script>
    var taxjar_validate_address = <?php echo $validateAddress ? "true" : "false"; ?>;
    var taxjar_validate_endpoint = '/rest/V1/Taxjar/address_validation/';
</script>
