<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<div id="tj-suggested-addresses" class="field" data-bind="scope: 'addressValidation'" style="display: none">
    <fieldset class="fieldset">
        <legend class="legend"><span>Suggested Addresses</span></legend>
        <!-- ko template: getTemplate() --><!-- /ko -->
    </fieldset>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "addressValidation": {
                    "component": "Taxjar_SalesTax/js/suggested_addresses_admin",
                    "template": "Taxjar_SalesTax/suggested_address_template",
                    "config": {
                        "controller": "<?php echo $block->getRequest()->getControllerName(); ?>",
                        "action": "<?php echo $block->getRequest()->getActionName(); ?>"
                    }
                }
            }
        }
    }
}
</script>
